= Kafka 101 Tutorial

A simple account balance management application to demonstrate how to write Kafka clients in Java. The application consists of the implementation of a producer, a consumer and a stream processor using Kafka APIs. User, who is identified by an ID number, can use producer service to send deposit or withdrawing request to the application. These requests are sequentially stored in a Kafka topic. User can also inspect all transactional events using consumer service or query the current balance from a materialized view generated by stream processor.

The program is written using Spring Boot to expose RESTful web services without much manual configuration.

How to run the application
=========================
* Start the Kafka cluster locally using default configuration.

* Create a Kafka topic named 'user-balance':
----
bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --topic user-balance
----

* Compile the project from the base directory:
----
./mvnw clean install
----

* A fat jar file will be generated in the target folder and can be started
----
java -jar kafka101-exec.jar
----

* After the application is started, the services are exposed at:
** localhost:8080/withdraw/{id}/{amount}: withdraw request for user with {id}.
** localhost:8080/deposit/{id}/{amount}: deposit request for user with {id}.
** localhost:8080/history: request the history of all transactions.
** localhost:8080/balance: show the balances of all users.
** localhost:8080/balance/{id}: show the balance of user with {id}.